name: Python package
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev dependencies
        run:  pip install -r requirements_test.txt
      - name: Run Linter
        #run:  "Trainee should add command to run flake8"
        run: python -m flake8 formation_indus_ds_avancee
      - name: Run Vulture
        #run:  "Trainee should add command to run vulture"
        run: vulture formation_indus_ds_avancee --min-confidence 100
      - name: Run tests
        #run:  "Trainee should add command to run test"
        run: python -m pytest tests/test_unit


